language: node_js
node_js:
  - node

branches:
  only:
  - master
sudo: false
cache:
  directories:
    - node_modules
env:
  secure: "Y/NMAFEx446egmMiAP6BOv4gHEWfscsN1HdW21xooox2hsjODZndl9EM/NE2/ylMy2pZ4UK6FReUv6e3XXn0w0psZOT/crHDZJWtrH7A2UcjboMgKxV/B/Sucnu5eztYLlUKLGkg6G+lvEiI6Uo0urkxCPZbY6vTBhK1dKxvGO5/qWIZrv1vftCNRAmDLp+bYlCRss5g1H5fDc2lj0/VKnj4JjeFock2ZenCHh5dCBt73cTYzYbJQDfcktiRWbqjVhbxbh5SuSNq5qNuQ0AuuySm+ZhQ0ie6fEtpcicsYDMmSgJIbr8ZULXwNMPjro/28YJjsN2+aOqN24iYYauZxtIsgUxYy8+vle8ppbQClZIxlIWtQcsrbAPRI2gX00X+G/lT3iYF9Ff0PWyXYlb7XcGUNoSpupy9RO+Sd5K5I/NdgkS3sME76DpSq1mscE98XyfE26dwVR7pRbeorG+VPA6wNoMoQsKqrOt7epcb9ArIFxPkh044Ot38Bg9lv1MuvJr8ak0teTIXbx4cC1wqpFbhvHas1HOLo9cxrPzx2YUdfsM/BsHMqQ/kx7cN6yDlAT3nL9W6jgaY6QQKpRmgfWVo3ugEIGvZK72m0Iw9gv0sGNoTH04CeL9FJDkNjD4lA3YGb9WVJVnye4uLxWTa84FLJP/CyBMexmz74s6fcSU="

before_script:
  - npm install -g grunt

script: grunt

before_deploy:
  - echo BEFORE DEPLOY
  - ./before_deploy.sh
  - echo TEST $DEPLOY

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: pj33efE+GnTQfoyE+wBy0fiNYJa3i5p+qGpL+crUoJJSIYiG0jV7aZX5YZDonp6I8UqY0QHTvJHDRRSOdMh1w0Ff0xVBOe7HhmzpQFCZAce3Td1mdKBUuscQJYVzudCcucJ6l5NXbumEOlISdQfv0/eO51DOpARqWjboV/kCrBE/FI9ouOnQeAD8oZwrIoNydZv41TkHDS60/lktOIq55Mt3QGcZ3RnOMcNnJuHLNhg4XJSCH4GrvNDVpAmBxg0AMyDNt5l21aqoo7a89Fs7o+zUw9OBN4/diP2niSAAotp4gUkW9y/BnEUuXBLE/cPQ+Wbr1Qz7TKXegvCr3vx3kvORjnTmSKty5UYaGmQV5yPKwCGAy8ZyO+uuVk9nu/Z7qVWVvxKzp7MvoVXUcqZKgNWYwDF7i1hnCWgEeGCs0ce7bZ7JPWzQMnI9MaHJSc5rhc6+KlyfZl5QDNSnO9ESnq/We7V0+VoxjjOONNJz0MNkYUqP1gjKjXqtrca5ZWHYKytiNgdsLgisk9JsD8OwNXjFbzXNu/44IFKQ+WOvyJpb+1BgS0zEAONjD7kYXEWUHwY6Px/HBBsrm6EM3fdvkZ1Vn9FSzYtK7iQi8hgQmY36ZyRYuCuMOANYXMvpDtMPDgF/VYaZkFr/jRe/yQw0riX7xoyiQrMTlZycIc/QANs=
  file:
    - realtimepolls-release.zip
    - realtimepolls-server.zip
  on:
    repo: g0ne/Realtime-Polls
    tags: false
    condition: $DEPLOY == "yes"

after_deploy:
  - echo AFTER DEPLOY
  - node travis_manage_git_releases.js
