language: node_js
node_js:
  - node
sudo: false
before_script:
  - npm install -g grunt
script: grunt
branches:
  only:
  - master
before_deploy:
  - git config --global user.email "buildbot@travis-ci.org"
  - git config --global user.name "Travis CI"
  - export RELEASE_VERSION=$(cat VERSION)
  - echo Version $RELEASE_VERSION
  - git tag -fa -m $RELEASE_VERSION $RELEASE_VERSION
  - git push -q --tags origin master
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: pj33efE+GnTQfoyE+wBy0fiNYJa3i5p+qGpL+crUoJJSIYiG0jV7aZX5YZDonp6I8UqY0QHTvJHDRRSOdMh1w0Ff0xVBOe7HhmzpQFCZAce3Td1mdKBUuscQJYVzudCcucJ6l5NXbumEOlISdQfv0/eO51DOpARqWjboV/kCrBE/FI9ouOnQeAD8oZwrIoNydZv41TkHDS60/lktOIq55Mt3QGcZ3RnOMcNnJuHLNhg4XJSCH4GrvNDVpAmBxg0AMyDNt5l21aqoo7a89Fs7o+zUw9OBN4/diP2niSAAotp4gUkW9y/BnEUuXBLE/cPQ+Wbr1Qz7TKXegvCr3vx3kvORjnTmSKty5UYaGmQV5yPKwCGAy8ZyO+uuVk9nu/Z7qVWVvxKzp7MvoVXUcqZKgNWYwDF7i1hnCWgEeGCs0ce7bZ7JPWzQMnI9MaHJSc5rhc6+KlyfZl5QDNSnO9ESnq/We7V0+VoxjjOONNJz0MNkYUqP1gjKjXqtrca5ZWHYKytiNgdsLgisk9JsD8OwNXjFbzXNu/44IFKQ+WOvyJpb+1BgS0zEAONjD7kYXEWUHwY6Px/HBBsrm6EM3fdvkZ1Vn9FSzYtK7iQi8hgQmY36ZyRYuCuMOANYXMvpDtMPDgF/VYaZkFr/jRe/yQw0riX7xoyiQrMTlZycIc/QANs=
  file:
    - realtimepolls-release.zip
    - realtimepolls-server.zip
  on:
    repo: g0ne/Realtime-Polls
    tags: false
