language: node_js
node_js:
  - node
sudo: false
before_script:
  - npm install -g grunt
script: grunt
branches:
  only:
  - master
before_deploy:
  - export RELEASE_VERSION=$(cat VERSION)
  - echo Version $RELEASE_VERSION
  - eval $(ssh-agent -s)
  - chmod 600 .travis/deploy_key.pem
  - ssh-add .travis/deploy_key.pem
  - git config --global user.email "buildbot@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git tag -fa -m $RELEASE_VERSION $RELEASE_VERSION
  - git remote add deploy https://$GITHUB_USER@github.com/$GITHUB_USER/$GITHUB_REPO
  - git push -qf --tags deploy master
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: pj33efE+GnTQfoyE+wBy0fiNYJa3i5p+qGpL+crUoJJSIYiG0jV7aZX5YZDonp6I8UqY0QHTvJHDRRSOdMh1w0Ff0xVBOe7HhmzpQFCZAce3Td1mdKBUuscQJYVzudCcucJ6l5NXbumEOlISdQfv0/eO51DOpARqWjboV/kCrBE/FI9ouOnQeAD8oZwrIoNydZv41TkHDS60/lktOIq55Mt3QGcZ3RnOMcNnJuHLNhg4XJSCH4GrvNDVpAmBxg0AMyDNt5l21aqoo7a89Fs7o+zUw9OBN4/diP2niSAAotp4gUkW9y/BnEUuXBLE/cPQ+Wbr1Qz7TKXegvCr3vx3kvORjnTmSKty5UYaGmQV5yPKwCGAy8ZyO+uuVk9nu/Z7qVWVvxKzp7MvoVXUcqZKgNWYwDF7i1hnCWgEeGCs0ce7bZ7JPWzQMnI9MaHJSc5rhc6+KlyfZl5QDNSnO9ESnq/We7V0+VoxjjOONNJz0MNkYUqP1gjKjXqtrca5ZWHYKytiNgdsLgisk9JsD8OwNXjFbzXNu/44IFKQ+WOvyJpb+1BgS0zEAONjD7kYXEWUHwY6Px/HBBsrm6EM3fdvkZ1Vn9FSzYtK7iQi8hgQmY36ZyRYuCuMOANYXMvpDtMPDgF/VYaZkFr/jRe/yQw0riX7xoyiQrMTlZycIc/QANs=
  file:
    - realtimepolls-release.zip
    - realtimepolls-server.zip
  on:
    repo: g0ne/Realtime-Polls
    tags: false
env:
  secure: "GWFcnPawaHFGl3jCxZIVfjNbuWNsBwPk75KMeb3CKkY2pjMX0ZxjED8++eO1IreVVlbxHhrvqEuQvOnQgNQTOcyEyP9bqcfu9OGuA1B84rr6gLxzciZjHtHg2cafA3ypizbAbZm85q096uyNh7V8dO6PBB61TgIIyApsMkLPh90x5vv/EXT7kMGZQPmOxI+b5JOu2/W38ErsY3kk+YeWfPJ5DJ0N2uOFpmsW/fKbhq9SjLZZebyj86UPZDj03EbFoUP3/lHtTHXaiZjSGMWeFebyln0r3TPC5f9iGB7hj7U+uWuOrwuZIUXWu5KY189g2sTPwo7M+2CUN/0Di5nPX7wO5eaYomrYsnuw5CdXuLshPLXenKzvNBClH+TMH5822nApb/JFf15x1PkjjcA7zUmYPXOq4PUP/mLI80Y/uFsmYSND2PfukD6ieqdaT+sAUPkjAMEz+K9dQhBTvP4qRZTqynRNhZcvBp8oY/MOP/xD7pwPg9yW9+l+ePuCymv62G0+0ExECWNZAQ0ECUMI8011yVlGPQDtCjYaR5hOanXfUy677soBAMbn4sWqbJIv1vCiwHan7DmdHvOEYCa685Bx0yep2AbHv1eD9A1iTZNKJJTec3E9sNPR5VR9M/drSxc6LmsGLbAzjnOSlzQM7VAmneFQ+Jc/9Av9J36ecso="
